services:
  mysql8-usuarios:
    container_name: mysql8-usuarios
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql-usuarios:/var/lib/mysql
    restart: always
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    build:
      context: ./
      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_HOST: mysql8-usuarios:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: root
      CURSOS_URL: msvc-cursos:8082
    networks:
      - spring
    depends_on:
      - mysql8-usuarios
    restart: always
volumes:
  data-mysql-usuarios:
    name: data-mysql-usuarios

networks:
  spring:
    name: "spring"