services:
  msvc-gateway:
    container_name: msvc-gateway
    build:
      context: ./
      dockerfile: ./msvc-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      USUARIOS_URL: ${USUARIOS_URL}
      CURSOS_URL: ${CURSOS_URL}
    networks:
      - spring
    depends_on:
    restart: always

volumes:

networks:
  spring:
    name: "spring"