services:
  mysql8-cursos:
    container_name: mysql8-cursos
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_cursos
    volumes:
      - data-mysql-cursos:/var/lib/mysql
    restart: always
    networks:
      - spring
  msvc-cursos:
    container_name: msvc-cursos
    build:
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      DB_HOST: mysql8-cursos:3306
      DB_DATABASE: msvc_cursos
      DB_USERNAME: root
      DB_PASSWORD: root

    networks:
      - spring
    depends_on:
      - mysql8-cursos
    restart: always
volumes:
  data-mysql-cursos:
    name: data-mysql-cursos

networks:
  spring:
    name: "spring"